"""Generate docs/site/data.js and docs/site/dashboard.js from the product.
Frozen snapshot — re-run when themes/panel_spec/renderers change.
Run: chiketi/.venv/bin/python scripts/gen_site_assets.py
"""
import json, pathlib, sys
ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from chiketi.panel_spec import web_spec
from chiketi.themes import get_families, get_active_family, get_active_theme

UI = ROOT / "chiketi" / "assets" / "ui"
OUT = ROOT / "docs" / "site"
OUT.mkdir(parents=True, exist_ok=True)

# --- 1. theme palettes: same shape as server.py /api/themes ---
THEME_FIELDS = ("primary","accent","background","panel","border","header","dim","critical")
families = {
    fam: {t.name: {f: getattr(t, f) for f in THEME_FIELDS} for t in themes}
    for fam, themes in get_families().items()
}
themes_blob = {"active_family": get_active_family(),
               "active_variant": get_active_theme().name,
               "families": families}

# --- 2. a curated demo metrics snapshot (nice-looking, not this machine) ---
def mval(value, unit="", extra=None, available=True):
    return {"value": value, "unit": unit, "available": available, "extra": extra or {}}
metrics = {
    "cpu.usage": mval(37, "%"), "cpu.per_core": mval([41,28,55,33,22,60,18,44]),
    "cpu.temp": mval(42), "cpu.mb_temp": mval(38), "cpu.fan": mval(1200),
    "cpu.fan_count": mval(2), "cpu.fans_cpu": mval([1200]), "cpu.fans_case": mval([900,950]),
    "mem.ram_used": mval(28.9, extra={"total":62.5,"percent":46}), "mem.ram_total": mval(62.5),
    "mem.ram_percent": mval(46, "%"), "mem.swap_used": mval(0, extra={"total":8,"percent":0}),
    "mem.swap_total": mval(8), "mem.swap_percent": mval(0, "%"),
    "disk.root_used": mval(0.41, extra={"total":1.0,"percent":41}), "disk.root_total": mval(1.0),
    "disk.root_percent": mval(41, "%"),
    "disk.home_used": mval(1200, extra={"total":4000,"percent":30}),
    "disk.home_total": mval(4000), "disk.home_percent": mval(30, "%"),
    "net.ip": mval("192.168.16.157"), "net.mac": mval("e8:9c:25:47:97:b6"),
    "net.speed": mval(1000), "net.dl": mval(2.7, "KB/s", {"raw_bytes_per_sec":2700}),
    "net.ul": mval(538.4, "KB/s", {"raw_bytes_per_sec":538400}),
    "sys.hostname": mval("mycroft"), "sys.uptime": mval("49d 2h 40m", extra={"seconds":4244400}),
    "gpu.name": mval("RTX 3090 Ti"), "gpu.temp": mval(50), "gpu.fan": mval(0),
    "gpu.power": mval(20, extra={"limit":450}), "gpu.vram_used": mval(22.0, extra={"total":24,"percent":92}),
    "gpu.vram_total": mval(24), "gpu.vram_percent": mval(92, "%"), "gpu.util": mval(0),
    "gpu.mem_util": mval(0), "gpu.clock_gpu": mval(210, extra={"max":2100}),
    "gpu.clock_mem": mval(405, extra={"max":10500}), "gpu.processes": mval([]),
    "llama.model": mval("Qwen3-32B"), "llama.quant": mval("Q4_K_M"), "llama.context": mval(12288),
    "llama.status": mval("running"), "llama.backend": mval("llama.cpp"),
    "llama.tok_per_sec": mval(38),
    "claude.tokens_total": mval(25100000), "claude.session_total": mval(20200000),
    "claude.sparkline": mval([3,5,8,6,9,12,7,15,11,18]), "claude.agents_active": mval(2),
    "claude.sessions": mval(140), "claude.days_active": mval(31), "claude.token_rate": mval(0),
}

data_js = (
    "// GENERATED by scripts/gen_site_assets.py — do not edit by hand.\n"
    "window.PANEL_SPEC = " + json.dumps(web_spec()) + ";\n"
    "window.SITE_THEMES = " + json.dumps(themes_blob) + ";\n"
    "window.SITE_METRICS = " + json.dumps(metrics) + ";\n"
)
(OUT / "data.js").write_text(data_js)

# --- 3. dashboard.js = shared_helpers + screen_functions + shim ---
shared = (UI / "shared_helpers.js").read_text()
screens = (UI / "screen_functions.js").read_text()
shim = r"""
/* ── site render shim (replaces display_app.js poll loop) ── */
var metrics = window.SITE_METRICS;
var activeFamily = null, activeVariant = null, themeColors = null;
function m(key){ if(!metrics||!metrics[key]) return {value:null,available:false,unit:'',extra:{}}; return metrics[key]; }
function mv(key,suffix){ var d=m(key); if(!d.available) return 'N/A'; return suffix? d.value+suffix : String(d.value); }
function cleanModel(){ var d=m('llama.model'); if(!d.available) return '--';
  return String(d.value).replace(/\.gguf$/i,'').replace(/[-_]Q\d[A-Z0-9_]*$/i,'').replace(/_/g,' ').replace(/-$/,''); }
function getScreen1Fn(){
  var isPanel=activeFamily==='Panel', isVintage=activeFamily==='Vintage';
  if(isPanel && activeVariant==='Teal') return panelTealScreen1;
  if(isPanel && activeVariant==='Coral') return panelCoralScreen1;
  if(isPanel) return panelGoldScreen1;
  if(isVintage && activeVariant==='Tubes') return tubeScreen1;
  if(isVintage && activeVariant==='VFD') return vfdScreen1;
  if(isVintage) return scanScreen1;
  return terminalScreen1;
}
/* Render theme's primary (System Stats) screen into element id `elId`. */
function renderThemeInto(elId, family, variant){
  activeFamily=family; activeVariant=variant;
  themeColors=((window.SITE_THEMES.families[family]||{})[variant])||null;
  if(!themeColors) return;
  document.getElementById(elId).innerHTML = getScreen1Fn()(themeColors);
}
window.renderThemeInto = renderThemeInto;
window.SITE_THEME_LIST = (function(){ var o=window.SITE_THEMES.families, a=[];
  for(var fam in o){ for(var v in o[fam]) a.push({family:fam, variant:v}); } return a; })();
"""
(OUT / "dashboard.js").write_text(
    "// GENERATED by scripts/gen_site_assets.py — do not edit by hand.\n"
    + shared + "\n" + screens + "\n" + shim)

# --- 4. dashboard.css = fonts.css + display.css, with font URLs made relative ---
# fonts.css @font-face rules use root-relative url('/assets/fonts/...'), which 404
# on a GitHub Pages PROJECT site (served at /chiketi/) and under file://. Rewrite
# them to be relative to docs/site/dashboard.css (fonts live at docs/assets/fonts/).
fonts_css = (UI / "fonts.css").read_text()
fonts_css = fonts_css.replace("url('/assets/fonts/", "url('../assets/fonts/")
fonts_css = fonts_css.replace('url("/assets/fonts/', 'url("../assets/fonts/')
display_css = (UI / "display.css").read_text()
# Mirror the product (server.py): substitute the url-rewritten fonts.css INTO the
# __FONTS_CSS__ placeholder in display.css. Concatenating instead would leave the
# literal token, forming a dead `__FONTS_CSS__ * {...}` selector that voids the reset.
(OUT / "dashboard.css").write_text(
    "/* GENERATED by scripts/gen_site_assets.py — do not edit by hand. */\n"
    + display_css.replace("__FONTS_CSS__", fonts_css))

print("wrote data.js (%d themes), dashboard.js, dashboard.css"
      % sum(len(v) for v in families.values()))
