"""Generate docs/site/data.js and docs/site/dashboard.js from the product.
Frozen snapshot — re-run when themes/panel_spec/renderers change.
Run: chiketi/.venv/bin/python scripts/gen_site_assets.py
"""
import json
import pathlib
import shutil
import subprocess
import sys
ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from chiketi.panel_spec import web_spec
from chiketi.themes import get_families, get_active_family, get_active_theme

UI = ROOT / "chiketi" / "assets" / "ui"
OUT = ROOT / "docs" / "site"
OUT.mkdir(parents=True, exist_ok=True)

# --- 1. theme palettes: same shape as server.py /api/themes ---
THEME_FIELDS = ("primary","accent","background","panel","border","header","dim","critical")
families = {
    fam: {t.name: {f: getattr(t, f) for f in THEME_FIELDS} for t in themes}
    for fam, themes in get_families().items()
}
themes_blob = {"active_family": get_active_family(),
               "active_variant": get_active_theme().name,
               "families": families}

# --- 2. demo metrics: the harness fixture, then a showroom overlay ---
# Hand-maintaining a second metric dict is how the site ends up rendering a
# screen's empty state: four keys the distro boards read (sys.kernel,
# sys.top_procs, net.iface, net.ping) were missing from BOTH this file and the
# fixture. tests/js/fixtures.js FULL is the one map a harness assertion keeps
# complete, so take it as the base and overlay only what makes the shot look
# like a real, good-looking machine rather than a test rig.
fixture_json = subprocess.run(
    ["node", "-e",
     "process.stdout.write(JSON.stringify(require(%s).FULL))"
     % json.dumps(str(ROOT / "tests" / "js" / "fixtures.js"))],
    check=True, capture_output=True, text=True, cwd=str(ROOT)).stdout
metrics = json.loads(fixture_json)


def mval(value, unit="", extra=None, available=True):
    return {"value": value, "unit": unit, "available": available, "extra": extra or {}}


metrics.update({
    "sys.hostname": mval("mycroft"),
    "sys.uptime": mval("49d 2h 40m", extra={"seconds": 4244400}),
    "net.ip": mval("192.168.16.157"),
    "net.mac": mval("e8:9c:25:47:97:b6"),
    "cpu.usage": mval(37, "%"),
    "cpu.per_core": mval([41, 28, 55, 33, 22, 60, 18, 44], "%"),
    "cpu.temp": mval(42, "°C"),
    "mem.ram_used": mval(28.9, "GiB", {"total": 62.5, "percent": 46}),
    "mem.ram_total": mval(62.5, "GiB"),
    "mem.ram_percent": mval(46, "%"),
    "llama.model": mval("Qwen3-32B"),
    "llama.quant": mval("Q4_K_M"),
    "llama.tok_per_sec": mval(38.4, "tok/s"),
    "claude.tokens_total": mval(25100000),
    "claude.session_total": mval(20200000),
    "claude.sessions": mval(140),
    "claude.days_active": mval(31),
})

data_js = (
    "// GENERATED by scripts/gen_site_assets.py — do not edit by hand.\n"
    "window.PANEL_SPEC = " + json.dumps(web_spec()) + ";\n"
    "window.SITE_THEMES = " + json.dumps(themes_blob) + ";\n"
    "window.SITE_METRICS = " + json.dumps(metrics) + ";\n"
)
(OUT / "data.js").write_text(data_js)

# --- 3. dashboard.js = shared_helpers + screen_functions + shim ---
shared = (UI / "shared_helpers.js").read_text()
screens = (UI / "screen_functions.js").read_text()
shim = r"""
/* ── site render shim (replaces display_app.js poll loop) ── */
var metrics = window.SITE_METRICS;
var activeFamily = null, activeVariant = null, themeColors = null;
function m(key){ if(!metrics||!metrics[key]) return {value:null,available:false,unit:'',extra:{}}; return metrics[key]; }
function mv(key,suffix){ var d=m(key); if(!d.available) return 'N/A'; return esc(suffix? d.value+suffix : String(d.value)); }
function cleanModel(){ var d=m('llama.model'); if(!d.available) return '--';
  return esc(String(d.value).replace(/\.gguf$/i,'').replace(/[-_]Q\d[A-Z0-9_]*$/i,'').replace(/_/g,' ').replace(/-$/,'')); }

/* Mirrors getScreenRegistry() in display_app.js. The site used to render only
   screen 1, which quietly made four fifths of the product invisible to anyone
   who had not installed it. */
function siteScreens(family, variant){
  var fns, second;
  if (family === 'Sci-Fi') {
    second = 'NPU';
    fns = variant === 'DS9' ? [sfDs9Screen1, sfDs9NpuScreen, sfDs9ClaudeScreen, sfDs9GpuScreen, sfDs9Screen2]
        : variant === 'TNG' ? [sfTngScreen1, sfTngNpuScreen, sfTngClaudeScreen, sfTngGpuScreen, sfTngScreen2]
                            : [sfTosScreen1, sfTosNpuScreen, sfTosClaudeScreen, sfTosGpuScreen, sfTosScreen2];
  } else if (family === 'Vintage') {
    second = 'NPU';
    fns = variant === 'Tubes' ? [tubeScreen1, tubeNpuScreen, tubeClaudeScreen, tubeGpuScreen, tubeScreen2]
        : variant === 'VFD'   ? [vfdScreen1, vfdNpuScreen, vfdClaudeScreen, vfdGpuScreen, vfdScreen2]
                              : [scanScreen1, scanNpuScreen, scanClaudeScreen, scanGpuScreen, scanScreen2];
  } else if (DISTRO_SCREENS[variant]) {
    second = 'AI Monitor';
    fns = [DISTRO_SCREENS[variant], DISTRO_AI_SCREENS[variant], DISTRO_CLAUDE_SCREENS[variant],
           DISTRO_GPU_SCREENS[variant], null];
  } else {
    second = 'AI Monitor';
    fns = [terminalScreen1, terminalScreen2, terminalClaudeScreen, terminalGpuScreen, null];
  }
  var out = [
    {name: 'System', fn: fns[0]},
    {name: second, fn: fns[1]},
    {name: 'Claude', fn: fns[2]},
    {name: 'GPU', fn: fns[3]},
  ];
  if (fns[4]) out.push({name: 'Clock', fn: fns[4]});
  return out;
}
window.SITE_SCREENS = siteScreens;

/* Render one screen of a theme into element `elId`. `screenIdx` defaults to the
   System Stats board; out-of-range indices clamp rather than blank the device. */
function renderThemeInto(elId, family, variant, screenIdx){
  var colors=((window.SITE_THEMES.families[family]||{})[variant])||null;
  if(!colors) return;  // bad/unknown theme: leave global state + current render intact.
  activeFamily=family; activeVariant=variant; themeColors=colors;
  var screens = siteScreens(family, variant);
  var i = Math.max(0, Math.min(screens.length - 1, screenIdx|0));
  document.getElementById(elId).innerHTML = screens[i].fn(themeColors);
}
window.renderThemeInto = renderThemeInto;
window.SITE_THEME_LIST = (function(){ var o=window.SITE_THEMES.families, a=[];
  for(var fam in o){ for(var v in o[fam]) a.push({family:fam, variant:v}); } return a; })();
"""
(OUT / "dashboard.js").write_text(
    "// GENERATED by scripts/gen_site_assets.py — do not edit by hand.\n"
    + shared + "\n" + screens + "\n" + shim)

# --- 4. dashboard.css = fonts.css + display.css, with font URLs made relative ---
# fonts.css @font-face rules use root-relative url('/assets/fonts/...'), which 404
# on a GitHub Pages PROJECT site (served at /chiketi/) and under file://. Rewrite
# them to be relative to docs/site/dashboard.css (fonts live at docs/assets/fonts/).
fonts_css = (UI / "fonts.css").read_text()
fonts_css = fonts_css.replace("url('/assets/fonts/", "url('../assets/fonts/")
fonts_css = fonts_css.replace('url("/assets/fonts/', 'url("../assets/fonts/')
display_css = (UI / "display.css").read_text()
# display.css is a full-screen KIOSK stylesheet: it sets html/body to a fixed
# 100vw/100vh, hides overflow, paints the background black, and hides the cursor.
# Those globals are correct on the kiosk page but BLEED onto the marketing page
# that @imports this file (non-scrollable, clipped, no cursor). Strip the
# kiosk-only html/body rule-sets here in the GENERATOR. Keep the `*` reset and
# all component classes (.t-*, .l-*, .screen-frame, etc.) intact.
display_css = display_css.replace(
    "  html, body { width: 100vw; height: 100vh; overflow: hidden; background: #000; }\n", "")
display_css = display_css.replace(
    "  body { cursor: none; }\n", "")
# SITE-ONLY: the Terminal-family (.t-*) layout uses FIXED PIXELS sized for the
# 1024px kiosk, so it overflows the ~430px hero device (Sci-Fi/Vintage use cqw and
# scale). For the generated site copy ONLY, convert the .t-* px dimensions to cqw
# (cqw = px / 1024 * 100). DO NOT touch the product display.css — the real kiosk
# relies on px + transform-scale. These are targeted, reproducible replacements.
_T_PX_TO_CQW = [
    # .t-screen { display: grid; gap: 6px; padding: 6px; ... }
    ("  .t-screen { display: grid; gap: 6px; padding: 6px; width: 100%; height: 100%; }",
     "  .t-screen { display: grid; gap: 0.586cqw; padding: 0.586cqw; width: 100%; height: 100%; }"),
    # .t-panel { padding: 14px 16px; ... }
    ("    padding: 14px 16px; overflow: hidden;",
     "    padding: 1.367cqw 1.5625cqw; overflow: hidden;"),
    # .t-title { font-size: 19px; margin-bottom: 12px; ... }
    ("    font-size: 19px; margin-bottom: 12px; white-space: nowrap;",
     "    font-size: 1.855cqw; margin-bottom: 1.172cqw; white-space: nowrap;"),
    # .t-row { ... gap: 8px; ... font-size: 17px; margin-bottom: 9px; ... }
    ("    display: flex; align-items: center; gap: 8px;",
     "    display: flex; align-items: center; gap: 0.781cqw;"),
    ("    font-size: 17px; margin-bottom: 9px; white-space: nowrap;",
     "    font-size: 1.66cqw; margin-bottom: 0.879cqw; white-space: nowrap;"),
    # .t-bar { ... height: 16px; ... font-size: 14px; ... line-height: 16px; }
    ("    flex: 1; height: 16px; display: flex; border-radius: 1px; overflow: hidden;",
     "    flex: 1; height: 1.5625cqw; display: flex; border-radius: 1px; overflow: hidden;"),
    ("    font-size: 14px; font-family: 'Consolas', monospace; line-height: 16px;",
     "    font-size: 1.367cqw; font-family: 'Consolas', monospace; line-height: 1.5625cqw;"),
]
for _old, _new in _T_PX_TO_CQW:
    assert _old in display_css, "gen_site_assets: .t-* anchor not found: %r" % _old
    display_css = display_css.replace(_old, _new)
# Mirror the product (server.py): substitute the url-rewritten fonts.css INTO the
# __FONTS_CSS__ placeholder in display.css. Concatenating instead would leave the
# literal token, forming a dead `__FONTS_CSS__ * {...}` selector that voids the reset.
(OUT / "dashboard.css").write_text(
    "/* GENERATED by scripts/gen_site_assets.py — do not edit by hand. */\n"
    + display_css.replace("__FONTS_CSS__", fonts_css))

# --- 5. mirror the font tree (TTFs AND licences) into docs/ ---
# GitHub Pages serves docs/ from a different root than the package, so docs/
# needs its own copy of the fonts. Sync it HERE rather than by hand: the OFL
# requires each licence to travel with its font, and a hand-copied tree is
# exactly how a licence gets left behind. Files present only in the destination
# are deleted, so a removed font cannot linger in the published site.
FONTS_SRC = ROOT / "chiketi" / "assets" / "fonts"
FONTS_DST = ROOT / "docs" / "assets" / "fonts"
FONTS_DST.mkdir(parents=True, exist_ok=True)
_wanted = set()
for f in sorted(FONTS_SRC.iterdir()):
    if f.is_file():
        _wanted.add(f.name)
        shutil.copy2(f, FONTS_DST / f.name)
for f in sorted(FONTS_DST.iterdir()):
    if f.is_file() and f.name not in _wanted:
        f.unlink()

print("wrote data.js (%d themes), dashboard.js, dashboard.css; mirrored %d font files"
      % (sum(len(v) for v in families.values()), len(_wanted)))
